name: Run clang-format to format code pushed to a branch with an active PR
run-name: Format source code

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Apparently, this is necessary in order to access the files?
      - uses: actions/checkout@v1
        with: 
          ref: ${{ github.head_ref }}
          
      - name: Run clang-format on the files in /src
        run: clang-format --verbose -i src/*
      - name: Commit and push changes
        run: |
          git config --global user.name "clang-format workflow"
          git config --global user.email "clang-format@actions.github.com"
          git branch -l
          git add .
          git commit -am "format: run clang-format."
          git push