name: Run clang-format to format code when a PR is accepted
run-name: Format merged code

on:
  pull_request:
    # types:
    #  - closed

jobs:
  if_merged:
    # if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Run clang-format
        working-directory: src
        run: clang-format --dry-run .