name: Run clang-format to format code when a PR is accepted
run-name: Format merged code

on:
  pull_request:
    # types:
    #  - closed

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Debug using ls
        working-directory: 
        run: | 
          ls -al