name: Run clang-format to format code pushed to a branch with an active PR
run-name: Format source code

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # - name: Run clang-format on the files in /src
      #   run: clang-format --verbose -i src/*
      - name: Commit and push changes
        run: |
          git remote add origin git@github.com:MuhammedReza07/dd1367-project.git
          git config --global user.name "clang-format workflow"
          git config --global user.email "clang-format@actions.github.com"
          