name: Run clang-format to format code pushed to a branch with an active PR
run-name: Format source code

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Apparently, this is necessary in order to access the files?
      - uses: actions/checkout@v6
        with: 
          ref: ${{ github.head_ref }}
          
      - name: Run clang-format on the files in /src
        run: clang-format --verbose -i src/*
      - name: Commit and push changes
        # ¯\_(ツ)_/¯ I just used the credentials I found at 
        # https://api.github.com/users/github-actions%5Bbot%5D.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -am "format: run clang-format."
          git push